# Model Building

Model Building (Baseline Validation Performance)
Before going further, I like to see how various different models perform with default parameters. I tried the following models using 5 fold cross validation to get a baseline. With a validation set basline, we can see how much tuning improves each of the models. 


* Decision Tree (75.1%)
* K Nearest Neighbor  (77.4%)
* **Random Forest       (80.2%)**
* Xtreme Gradient Boosting (74.5%)
* Soft Voting Classifier - All Models (79.5%)

In [1]:
# Import libraries and data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
path ='/Users/apple/Documents/Github/Water_Pump_Classification/Data/'

In [2]:
X_train = pd.read_csv(path+"X_train_scaled.csv",index_col='id');
X_test = pd.read_csv(path+"X_test_scaled.csv", index_col='id');
y_train = pd.read_csv(path +"Training_label.csv",index_col='id') 

In [3]:
y_train = y_train['status_group']

In [4]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [5]:
dt = DecisionTreeClassifier(random_state = 1)
cv = cross_val_score(dt,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.75153607 0.74825351 0.7543771  0.74983165 0.74962115]
0.7507238965103818


In [6]:
knn = KNeighborsClassifier()
cv = cross_val_score(knn,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.77914317 0.77215723 0.77407407 0.77314815 0.77294157]
0.7742928380934295


In [7]:
rf = RandomForestClassifier(random_state = 1, n_estimators=100)
cv = cross_val_score(rf,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.80254187 0.80018517 0.80462963 0.79974747 0.80156592]
0.8017340135487743


In [8]:
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state =1)
cv = cross_val_score(xgb,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.74741183 0.73849003 0.74225589 0.74259259 0.75265196]
0.7446804613141937


In [9]:
from sklearn.ensemble import VotingClassifier
voting_clf = VotingClassifier(estimators = [('dt',dt),('knn',knn),('rf',rf),('xgb',xgb)], voting = 'soft') 

In [10]:
cv = cross_val_score(voting_clf,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.79673428 0.79370423 0.79385522 0.79040404 0.79499916]
0.7939393865286354
